
# This file is used to configure your Supabase project.
# It's very important to not share or leak this file as it contains your project's secrets.
# You should not modify this file manually.

project_id = "ledtlqrtkblzchxzrwkk"

[api]
# Port to use for the API URL.
port = 54321
# Schemas to expose in your API. Tables, views and stored procedures in this schema will get API
# endpoints. public and storage are always included.
schemas = ["public", "storage", "graphql_public"]
# Extra schemas to add to the search_path of every request. public is always included.
extra_search_path = ["public", "extensions"]
# Maximum rows returns in a single response
max_rows = 1000

[db]
# Port to use for the local database URL.
port = 54322
# Port used by psql when connecting to the database
psql_port = 54320
# The database major version to use. This has to be the same as your remote database's. Run `SHOW
# server_version;` on the remote database to check.
major_version = 15

[studio]
enabled = true
# Port to use for Supabase Studio.
port = 54323
# API URL used by Supabase Studio. Same as SUPABASE_URL, but uses localhost
api_url = "http://localhost:54321"

[inbucket]
# Port to use for the email testing server's SMTP port.
smtp_port = 54325
# Port to use for the email testing server's POP3 port.
pop3_port = 54326
# Port to use for the email testing server's web interface.
ui_port = 54324

[auth]
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "http://localhost:3000"
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = ["https://localhost:3000"]
# How long tokens are valid for, in seconds. Defaults to 3600 (1 hour), maximum 604,800 (1 week).
jwt_expiry = 3600
# If disabled, the refresh token will never expire.
enable_refresh_token_rotation = true
# Allows refresh tokens to be reused after expiry, up to the specified interval in seconds.
# Requires enable_refresh_token_rotation = true.
refresh_token_reuse_interval = 10
# Allow/disallow new user signups to your project.
enable_signup = true

[auth.email]
# Allow/disallow new user signups via email to your project.
enable_signup = true
# If enabled, a user will be required to confirm any email change on both the old, and new email
# addresses. If disabled, only the new email is required to confirm.
double_confirm_changes = true
# If enabled, users need to confirm their email address before signing in.
enable_confirmations = false

[auth.sms]
# Allow/disallow new user signups via SMS to your project.
enable_signup = true
# If enabled, users need to confirm their phone number before signing in.
enable_confirmations = false

# Configure one of the supported SMS providers: `twilio`, `messagebird`, `textlocal`, `vonage`.
[auth.sms.twilio]
enabled = false
account_sid = ""
message_service_sid = ""
# DO NOT COMMIT YOUR TWILIO AUTH TOKEN
auth_token = ""

[auth.external.github]
enabled = false
client_id = ""
# DO NOT COMMIT YOUR GITHUB AUTH SECRET
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""
# Overrides the default auth provider URL. Used to support self-hosted github enterprise.
url = ""

[auth.external.google]
enabled = false
client_id = ""
# DO NOT COMMIT YOUR GOOGLE AUTH SECRET
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""
# Overrides the default auth provider URL.
url = ""

[functions]
# Port to use for Functions locally.
port = 54321

[realtime]
enabled = true
# How many simultaneous Realtime connections one user can have
user_connection_limit = 10
# Hide stop word metrics in the console for SQL subscribers
hide_stop_word_metrics = false

[analytics]
enabled = false
port = 54327
vector_port = 54328
# Configure one of the supported backends: `postgres`, `bigquery`, `snowflake`.
backend = "postgres"

# Configures Postgres backend.
[analytics.postgres]
# The maximum number of pooled connections to the analytics database.
pool_max_conns = 10
# The maximum duration to wait while connecting to a database in the pool.
pool_timeout_seconds = 30
# how long connections in the pool can remain idle before they are closed.
pool_max_idle_seconds = 300
# The maximum lifetime of a connection in the pool. This should be lower than any server-side
# connection timeouts. (Note that seconds here is not a typo for milliseconds.)
pool_max_lifetime_seconds = 3600
# how often to collect pool metrics (in seconds)
metrics_interval_seconds = 30

[extensions]
enabled = false
