// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ledtlqrtkblzchxzrwkk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxlZHRscXJ0a2JsemNoeHpyd2trIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MzAzMjEsImV4cCI6MjA2MTAwNjMyMX0.e0PlpTWwbAuIhc-EHEV1pHnzzjBptYNWm25r6m2y2nk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);